---
parent: Api_v1_envs_validate_auths
name: EnvironmentCreateUserAInitAbact3
description: Desc
authors:
- apisec Bot
type: ABSTRACT
init: []
localVariables: []
path: /api/v1/envs/validate/auths
endpoint: /api/v1/envs/validate/auths
method: POST
auth: UserA
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "baseUrl" : "{{@Random}}",
      "createdBy" : "",
      "createdDate" : "",
      "description" : "{{@Random}}",
      "endpoint" : "{{@Random}}",
      "id" : "",
      "inactive" : false,
      "issueTracker" : {
        "account" : "{{@Random}}",
        "accountType" : "Wrike",
        "id" : "",
        "issueType" : "{{@Random}}",
        "name" : "{{@Random}}",
        "projectKey" : "{{@Random}}",
        "url" : "{{@Random}}"
      },
      "localOffSet" : "{{@RandomInteger}}",
      "modifiedBy" : "",
      "modifiedDate" : "",
      "name" : "{{@Random}}",
      "projectCreation" : false,
      "projectId" : "{{@ProjectCreateUserAInitAbact3_Response.data.id}}",
      "reachable" : false,
      "refId" : "{{@Random}}",
      "region" : "{{@Random}}",
      "url" : "{{@Random}}",
      "urlReachableOn" : null,
      "version" : ""
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode == 200 OR @StatusCode == 201'
cleanup:
- ApiV1ProjectsRequestidEnvRequestidDeleteEnvironmentabact3
severity: High
category: ABAC_Level3
tags:
- V1
- Data_Access_Control
- '[2020 CWE TOP 22 ] CWE - 269'
- OWASP-API1
- OWASP API Security Top 10
- '[PCI DSS 3.2.1] 6.5.8'
- Broken Object Level Authorization
- Penetration Testing
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
