---
parent: Api_v1_autocode-generator
name: ApiV1AutocodeGeneratorPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/autocode-generator
endpoint: /api/v1/autocode-generator
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "abacResources" : [ {
        "createBody" : "{{@Random}}",
        "createEndpoint" : "{{@Random}}",
        "createUserAuth" : "{{@Random}}",
        "createdBy" : "",
        "createdDate" : "",
        "deleteEndpoint" : "{{@Random}}",
        "enumValues" : "{{@Random}}",
        "generatorId" : "{{@Random}}",
        "id" : "",
        "inactive" : false,
        "initScriptName" : "{{@Random}}",
        "lock" : false,
        "modifiedBy" : "",
        "modifiedDate" : "",
        "resourceName" : "{{@Random}}",
        "scripts" : [ {
          "body" : "{{@Random}}",
          "deleteEndPoint" : "{{@Random}}",
          "endpoint" : "{{@Random}}",
          "resourceName" : "{{@Random}}",
          "scriptName" : "{{@Random}}",
          "scriptType" : "{{@Random}}",
          "sequence" : "{{@RandomInteger}}",
          "userAuth" : "{{@Random}}",
          "validationScript" : false
        } ],
        "typeThreeCreateEndpoint" : "{{@Random}}",
        "validations" : [ {
          "body" : "{{@Random}}",
          "endpoint" : "{{@Random}}",
          "inactive" : false,
          "lock" : false,
          "path" : "{{@Random}}",
          "userAuth" : "{{@Random}}",
          "validationType" : "{{@Random}}"
        } ],
        "version" : ""
      } ],
      "activatedDate" : null,
      "activeByDefault" : false,
      "activityAction" : "{{@Var.activityAction}}",
      "activityText" : "{{@Var.activityText}}",
      "addOptionalParams" : false,
      "assertionDescription" : "{{@Var.assertionDescription}}",
      "assertions" : [ "{{@Random}}" ],
      "assertionsText" : "{{@Var.assertionsText}}",
      "auth" : "{{@Var.auth}}",
      "authors" : "{{@Var.authors}}",
      "beta" : false,
      "bountyValue" : "{{@Var.bountyValue}}",
      "category" : "{{@Var.category}}",
      "categoryGroup" : "{{@Var.categoryGroup}}",
      "coverageMultiplier" : "{{@Var.coverageMultiplier}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "currentScripts" : "{{@Var.currentScripts}}",
      "customHeaders" : "{{@Var.customHeaders}}",
      "customType" : "{{@Var.customType}}",
      "cvssScore" : "{{@Var.cvssScore}}",
      "cvssScoreType" : "{{@Var.cvssScoreType}}",
      "database" : {
        "name" : "{{@Var.name}}",
        "version" : "{{@Var.version}}"
      },
      "displayHeaderDescription" : "{{@Var.displayHeaderDescription}}",
      "displayHeaderLabel" : "{{@Var.displayHeaderLabel}}",
      "endpointSelection" : "{{@Var.endpointSelection}}",
      "expectedScripts" : "{{@Var.expectedScripts}}",
      "fixHours" : "{{@Var.fixHours}}",
      "id" : "{{@Var.id}}",
      "imageUrl" : "{{@Var.imageUrl}}",
      "inactive" : false,
      "lastModifiedByUser" : "{{@Var.lastModifiedByUser}}",
      "matches" : [ {
        "allowRoles" : "{{@Random}}",
        "bodyProperties" : "{{@Random}}",
        "denyRoles" : "{{@Random}}",
        "id" : "",
        "methods" : "{{@Random}}",
        "name" : "{{@Random}}",
        "pathPatterns" : "{{@Random}}",
        "queryParams" : "{{@Random}}",
        "resourceSamples" : "{{@Random}}",
        "value" : "{{@Random}}"
      } ],
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "newlyAdded" : false,
      "owner" : "{{@Var.owner}}",
      "payloads" : [ {
        "categoryGroup" : "DEFAULT",
        "createdBy" : "",
        "createdDate" : "",
        "endpoint" : "{{@Random}}",
        "example" : "{{@Random}}",
        "id" : "",
        "inactive" : false,
        "locked" : false,
        "method" : "{{@Random}}",
        "modifiedBy" : "",
        "modifiedDate" : "",
        "payload" : "{{@Random}}",
        "projectId" : "{{@Random}}",
        "resourceName" : "{{@Random}}",
        "version" : ""
      } ],
      "project" : {
        "account" : {
          "accountType" : "{{@Var.accountType}}",
          "createdBy" : "{{@Var.createdBy}}",
          "createdDate" : "{{@Var.createdDate}}",
          "id" : "{{@Var.id}}",
          "inactive" : false,
          "isSSH" : false,
          "modifiedBy" : "{{@Var.modifiedBy}}",
          "modifiedDate" : "{{@Var.modifiedDate}}",
          "name" : "{{@Var.name}}",
          "org" : {
            "createdBy" : "{{@Var.createdBy}}",
            "createdDate" : "{{@Var.createdDate}}",
            "id" : "{{@Var.id}}",
            "inactive" : false,
            "modifiedBy" : "{{@Var.modifiedBy}}",
            "modifiedDate" : "{{@Var.modifiedDate}}",
            "name" : "{{@Var.name}}",
            "orgPlan" : "{{@Var.orgPlan}}",
            "version" : "{{@Var.version}}"
          },
          "region" : "{{@Var.region}}",
          "version" : "{{@Var.version}}"
        },
        "activateScheduledReports" : false,
        "activeGenerators" : [ "{{@Random}}" ],
        "apiGatewayAccountType" : "{{@Var.apiGatewayAccountType}}",
        "apiGatewayId" : "{{@Var.apiGatewayId}}",
        "apiGroupId" : "{{@Var.apiGroupId}}",
        "apiId" : "{{@Var.apiId}}",
        "apiType" : "{{@Var.apiType}}",
        "autoGenSuites" : "{{@Var.autoGenSuites}}",
        "baseUrl" : "{{@Var.baseUrl}}",
        "branch" : "{{@Var.branch}}",
        "bugsClosed" : "{{@Var.bugsClosed}}",
        "bugsOpen" : "{{@Var.bugsOpen}}",
        "coverage" : "{{@Var.coverage}}",
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "description" : "{{@Var.description}}",
        "endpointsCount" : "{{@Var.endpointsCount}}",
        "entitledUsers" : [ {
          "email" : "{{@Faker.internet.emailAddress}}",
          "entitlementType" : "SECURITY_RESEARCHER",
          "projectId" : "{{@Random}}",
          "userId" : "{{@Random}}"
        } ],
        "envReachable" : false,
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "isFileLoad" : "{{@Var.isFileLoad}}",
        "issueTracker" : {
          "account" : "{{@Var.account}}",
          "accountType" : "{{@Var.accountType}}",
          "id" : "{{@Var.id}}",
          "issueType" : "{{@Var.issueType}}",
          "name" : "{{@Var.name}}",
          "projectKey" : "{{@Var.projectKey}}",
          "url" : "{{@Var.url}}"
        },
        "lastCommit" : "{{@Var.lastCommit}}",
        "lastRunCreation" : null,
        "lastSync" : null,
        "licenses" : [ "{{@Random}}" ],
        "localOffSet" : "{{@Var.localOffSet}}",
        "manualEpFound" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "noApi" : false,
        "nonWorkingPlaybooksCount" : "{{@Var.nonWorkingPlaybooksCount}}",
        "nonWorkingPlaybooksPercentage" : "{{@Var.nonWorkingPlaybooksPercentage}}",
        "notifications" : [ {
          "account" : "{{@Random}}",
          "channel" : "{{@Random}}",
          "id" : "",
          "name" : "{{@Random}}",
          "to" : "{{@Random}}"
        } ],
        "openAPISpec" : "{{@Var.openAPISpec}}",
        "openText" : "{{@Var.openText}}",
        "org" : {
          "createdBy" : "{{@Var.createdBy}}",
          "createdDate" : "{{@Var.createdDate}}",
          "id" : "{{@Var.id}}",
          "inactive" : false,
          "modifiedBy" : "{{@Var.modifiedBy}}",
          "modifiedDate" : "{{@Var.modifiedDate}}",
          "name" : "{{@Var.name}}",
          "orgPlan" : "{{@Var.orgPlan}}",
          "version" : "{{@Var.version}}"
        },
        "owner" : "{{@Var.owner}}",
        "personalizedCoverage" : {
          "auths" : [ {
            "accessTokenUri" : "{{@Random}}",
            "authType" : "No_Authentication",
            "authorizationScheme" : "query",
            "body" : "{{@Random}}",
            "clientAuthenticationScheme" : "query",
            "clientId" : "{{@Random}}",
            "clientSecret" : "{{@Random}}",
            "cmdCache" : "{{@Random}}",
            "contentType" : "{{@Random}}",
            "curlHeaders" : "{{@Random}}",
            "curlRequest" : "{{@Random}}",
            "curlResponse" : "{{@Random}}",
            "curlUrl" : "{{@Random}}",
            "curlVariables" : "{{@Random}}",
            "endpoint" : "{{@Random}}",
            "grantType" : "password",
            "header_1" : "{{@Random}}",
            "header_2" : "{{@Random}}",
            "header_3" : "{{@Random}}",
            "id" : "",
            "inactive" : false,
            "invalid" : false,
            "lastTestedOn" : null,
            "method" : "{{@Random}}",
            "methodToken" : "{{@Random}}",
            "name" : "{{@Random}}",
            "password" : "{{@PassAlphaNumSpl}}",
            "passwordMasked" : false,
            "preEstablishedRedirectUri" : "{{@Random}}",
            "preScript" : "{{@Random}}",
            "scope" : "{{@Random}}",
            "tokenAccess" : "{{@Random}}",
            "tokenName" : "{{@Random}}",
            "useCurrentUri" : false,
            "userAuthorizationUri" : "{{@Random}}",
            "username" : "{{@Faker.name.username}}"
          } ],
          "commandChecks" : "{{@Var.commandChecks}}",
          "createdBy" : { },
          "createdDate" : "{{@Var.createdDate}}",
          "cron" : "{{@Var.cron}}",
          "databases" : "{{@Var.databases}}",
          "email" : "{{@Var.email}}",
          "id" : "{{@Var.id}}",
          "inactive" : false,
          "modifiedBy" : { },
          "modifiedDate" : "{{@Var.modifiedDate}}",
          "projectId" : "{{@Var.projectId}}",
          "roles" : "{{@Var.roles}}",
          "timeZone" : "{{@Var.timeZone}}",
          "tokenExample" : "{{@Var.tokenExample}}",
          "version" : "{{@Var.version}}"
        },
        "planType" : "{{@Var.planType}}",
        "playbooksCount" : "{{@Var.playbooksCount}}",
        "props" : null,
        "region" : "{{@Var.region}}",
        "skipAbac" : false,
        "skipGitbackup" : false,
        "source" : "{{@Var.source}}",
        "stage" : "{{@Var.stage}}",
        "status" : "{{@Var.status}}",
        "swaggerEditorOas" : "{{@Var.swaggerEditorOas}}",
        "tags" : [ "{{@Random}}" ],
        "url" : "{{@Var.url}}",
        "urlReachableOn" : null,
        "validation" : false,
        "version" : "{{@Var.version}}"
      },
      "rank" : "{{@Var.rank}}",
      "researchers" : "{{@Var.researchers}}",
      "saveAction" : false,
      "sequenceOrder" : "{{@Var.sequenceOrder}}",
      "severity" : "{{@Var.severity}}",
      "showResponse" : false,
      "skipVulnerabilityFiling" : false,
      "supportedParams" : "{{@Var.supportedParams}}",
      "tags" : [ "{{@Random}}" ],
      "type" : "{{@Var.type}}",
      "useCategoryAssertion" : false,
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
