---
parent: Api_v1_system-settings
name: ApiV1SystemSettingsPutBodyParamReflectedPostInjection
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/system-settings
endpoint: /api/v1/system-settings
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "key" : "{{@Injection}}",
      "label" : "{{@Injection}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "value" : "{{@Injection}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@Response !=~ (?s:.)*<(?s:.*)(injectionReflection)(?s:.*)>(?s:.*)'
cleanup: []
severity: High
category: reflected_post_injection
tags:
- V1
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@APIsec/Common/reflected_post_injection'
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
