---
parent: Api_v1_resources_project_projectid
name: ApiV1ResourcesProjectProjectidPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/resources/project/{projectId}
endpoint: /api/v1/resources/project/{{@Var.projectId}}
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "definition" : "{{@Var.definition}}",
      "dependency" : "{{@Var.dependency}}",
      "endpoints" : [ {
        "coverageStatus" : { },
        "description" : "{{@Random}}",
        "endpoint" : "{{@Random}}",
        "isMapped" : false,
        "manualEndpoint" : false,
        "method" : "{{@Random}}",
        "parameters" : [ {
          "body" : "{{@Random}}",
          "defaultValue" : "{{@Random}}",
          "description" : "{{@Random}}",
          "endpointId" : "{{@Random}}",
          "enums" : "{{@Random}}",
          "example" : "{{@Random}}",
          "format" : "{{@Random}}",
          "in" : "{{@Random}}",
          "name" : "{{@Random}}",
          "required" : false,
          "type" : "{{@Random}}"
        } ],
        "pathDependency" : "{{@Random}}",
        "payload" : "{{@Random}}",
        "projectId" : "{{@Random}}",
        "queryDependency" : "{{@Random}}",
        "resourceName" : "{{@Random}}",
        "responses" : [ {
          "contentType" : "{{@Random}}",
          "endpointId" : "{{@Random}}",
          "ref" : "{{@Random}}",
          "response" : "{{@Random}}",
          "responsePii" : "{{@Random}}",
          "responseStatus" : "{{@Random}}"
        } ],
        "sequenceOrder" : "{{@RandomInteger}}",
        "summary" : "{{@Random}}",
        "tags" : "{{@Random}}",
        "typeThreePath" : "{{@Random}}"
      } ],
      "enumValues" : "{{@Var.enumValues}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "path" : "{{@Var.path}}",
      "projectId" : "{{@Var.projectId}}",
      "resourceName" : "{{@Var.resourceName}}",
      "tags" : "{{@Var.tags}}",
      "typeThreeDefination" : "{{@Var.typeThreeDefination}}",
      "typeThreePath" : "{{@Var.typeThreePath}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
