---
parent: Api_v1_abac
name: ApiV1AbacPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/abac
endpoint: /api/v1/abac
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "createBody" : "{{@Var.createBody}}",
      "createEndpoint" : "{{@Var.createEndpoint}}",
      "createUserAuth" : "{{@Var.createUserAuth}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "deleteEndpoint" : "{{@Var.deleteEndpoint}}",
      "enumValues" : "{{@Var.enumValues}}",
      "generatorId" : "{{@Var.generatorId}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "initScriptName" : "{{@Var.initScriptName}}",
      "lock" : false,
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "resourceName" : "{{@Var.resourceName}}",
      "scripts" : [ {
        "body" : "{{@Random}}",
        "deleteEndPoint" : "{{@Random}}",
        "endpoint" : "{{@Random}}",
        "resourceName" : "{{@Random}}",
        "scriptName" : "{{@Random}}",
        "scriptType" : "{{@Random}}",
        "sequence" : "{{@RandomInteger}}",
        "userAuth" : "{{@Random}}",
        "validationScript" : false
      } ],
      "typeThreeCreateEndpoint" : "{{@Var.typeThreeCreateEndpoint}}",
      "validations" : [ {
        "body" : "{{@Random}}",
        "endpoint" : "{{@Random}}",
        "inactive" : false,
        "lock" : false,
        "path" : "{{@Random}}",
        "userAuth" : "{{@Random}}",
        "validationType" : "{{@Random}}"
      } ],
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
