---
parent: Api_v1_system-settings_save
name: ApiV1SystemSettingsSavePostAnonymousInvalid
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/system-settings/save
endpoint: /api/v1/system-settings/save
method: POST
auth: Anonymous
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    [ {
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "key" : "{{@Var.key}}",
      "label" : "{{@Var.label}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "value" : "{{@Var.value}}",
      "version" : "{{@Var.version}}"
    } ]
  inactive: false
useCategoryAssertion: false
assertions:
- '@StatusCode == 401 OR @StatusCode == 403 OR @StatusCode == 404'
cleanup: []
severity: Critical
category: Unsecured
tags:
- V1
- Broken Authentication
- Non-Intrusive
- '[2020 CWE TOP 24] CWE - 306'
- OWASP-API2
- OWASP - OTG-AUTHN-002
- OWASP API Security Top 10
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
