---
parent: Api_v1_teams
name: ApiV1TeamsPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/teams
endpoint: /api/v1/teams
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "description" : "{{@Var.description}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "name" : "{{@Var.name}}",
      "org" : {
        "authorizationEndpoiont" : "{{@Var.authorizationEndpoiont}}",
        "billingEmail" : "{{@Var.billingEmail}}",
        "clientId" : "{{@Var.clientId}}",
        "company" : "{{@Var.company}}",
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "description" : "{{@Var.description}}",
        "enterpriseLicense" : "{{@Var.enterpriseLicense}}",
        "freeLicense" : "{{@Var.freeLicense}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "issuer" : "{{@Var.issuer}}",
        "location" : "{{@Var.location}}",
        "mfaEnabled" : false,
        "mfaEnabledDate" : null,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "oidcEndpoiont" : "{{@Var.oidcEndpoiont}}",
        "orgPlan" : "{{@Var.orgPlan}}",
        "orgTag" : "{{@Var.orgTag}}",
        "orgType" : "{{@Var.orgType}}",
        "ownerName" : "{{@Var.ownerName}}",
        "referrer" : "{{@Var.referrer}}",
        "ssoEnabled" : false,
        "ssoType" : "{{@Var.ssoType}}",
        "suiteValidationLimit" : "{{@Var.suiteValidationLimit}}",
        "tokenEndpoiont" : "{{@Var.tokenEndpoiont}}",
        "url" : "{{@Var.url}}",
        "usedEntLicense" : "{{@Var.usedEntLicense}}",
        "version" : "{{@Var.version}}"
      },
      "users" : [ {
        "accountNonExpired" : false,
        "accountNonLocked" : false,
        "company" : "{{@Faker.company.name}}",
        "createdBy" : "",
        "createdDate" : "",
        "credentialsNonExpired" : false,
        "email" : "{{@Faker.internet.emailAddress}}",
        "enabled" : false,
        "id" : "",
        "inactive" : false,
        "jobTitle" : "{{@Faker.job.title}}",
        "lastAccessTime" : null,
        "location" : "{{@Random}}",
        "mfa" : false,
        "mfaEnabledAtOrg" : false,
        "modifiedBy" : "",
        "modifiedDate" : "",
        "name" : "{{@Random}}",
        "otp" : "{{@Random}}",
        "password" : "{{@PassAlphaNumSpl}}",
        "privileges" : [ "{{@Random}}" ],
        "qrCode" : "{{@Random}}",
        "secret" : "{{@Random}}",
        "successfulLoginAttempts" : "{{@RandomInteger}}",
        "unsuccessfulLoginAttempts" : "{{@RandomInteger}}",
        "username" : "{{@Faker.name.username}}",
        "version" : ""
      } ],
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
