---
parent: Api_v1_endpoint_project_id
name: ApiV1EndpointProjectIdPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/endpoint/project/{id}
endpoint: /api/v1/endpoint/project/{{@Var.id}}
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    [ {
      "coverageStatus" : { },
      "description" : "{{@Var.description}}",
      "endpoint" : "{{@Var.endpoint}}",
      "isMapped" : false,
      "manualEndpoint" : false,
      "method" : "{{@Var.method}}",
      "parameters" : [ {
        "body" : "{{@Random}}",
        "defaultValue" : "{{@Random}}",
        "description" : "{{@Random}}",
        "endpointId" : "{{@Random}}",
        "enums" : "{{@Random}}",
        "example" : "{{@Random}}",
        "format" : "{{@Random}}",
        "in" : "{{@Random}}",
        "name" : "{{@Random}}",
        "required" : false,
        "type" : "{{@Random}}"
      } ],
      "pathDependency" : "{{@Var.pathDependency}}",
      "payload" : "{{@Var.payload}}",
      "projectId" : "{{@Var.projectId}}",
      "queryDependency" : "{{@Var.queryDependency}}",
      "resourceName" : "{{@Var.resourceName}}",
      "responses" : [ {
        "contentType" : "{{@Random}}",
        "endpointId" : "{{@Random}}",
        "ref" : "{{@Random}}",
        "response" : "{{@Random}}",
        "responsePii" : "{{@Random}}",
        "responseStatus" : "{{@Random}}"
      } ],
      "sequenceOrder" : "{{@Var.sequenceOrder}}",
      "summary" : "{{@Var.summary}}",
      "tags" : "{{@Var.tags}}",
      "typeThreePath" : "{{@Var.typeThreePath}}"
    } ]
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
