---
parent: Api_v1_accounts_id
name: ApiV1AccountsIdPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/accounts/{id}
endpoint: /api/v1/accounts/{{@Var.id}}
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "accessKey" : "{{@Var.accessKey}}",
      "accountType" : "{{@Var.accountType}}",
      "allowedRegions" : [ "{{@Random}}" ],
      "autoOnboard" : false,
      "bucketName" : "{{@Var.bucketName}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "isDefaultStore" : false,
      "isSSH" : false,
      "isdefault" : false,
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "name" : "{{@Var.name}}",
      "org" : {
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "orgPlan" : "{{@Var.orgPlan}}",
        "version" : "{{@Var.version}}"
      },
      "ownerName" : "{{@Var.ownerName}}",
      "prop1" : "{{@Var.prop1}}",
      "prop2" : "{{@Var.prop2}}",
      "prop3" : "{{@Var.prop3}}",
      "region" : "{{@Var.region}}",
      "secretKey" : "{{@Var.secretKey}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
