---
parent: Api_v1_generator-configuration
name: ApiV1GeneratorConfigurationPostBodyParamSsrfExternalUrl
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/generator-configuration
endpoint: /api/v1/generator-configuration
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
testCases:
- id: 1
  body: |-
    {
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "generatorType" : "{{@Injection}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "projectId" : "{{@Injection}}",
      "resourceMapping" : null,
      "resourceMappingList" : [ {
        "key" : "{{@Random}}",
        "value" : "{{@Random}}"
      } ],
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@Response !=~ (?s:.)*<(?s:.*)(APISec External SSRF)(?s:.*)>(?s:.*)'
- '@ResponseTime < 7000 OR @StatusCode == 400'
cleanup: []
severity: High
category: ssrf_external_url
tags:
- V1
- OWASP-API8
- OWASP API Security Top 10
- SSRF
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: '@APIsec/Common/ssrf_external_url'
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
