---
parent: Api_v1_bot-clusters
name: ApiV1BotClustersPostCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/bot-clusters
endpoint: /api/v1/bot-clusters
method: POST
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "account" : {
        "accountType" : "{{@Var.accountType}}",
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "isSSH" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "org" : {
          "createdBy" : "{{@Var.createdBy}}",
          "createdDate" : "{{@Var.createdDate}}",
          "id" : "{{@Var.id}}",
          "inactive" : false,
          "modifiedBy" : "{{@Var.modifiedBy}}",
          "modifiedDate" : "{{@Var.modifiedDate}}",
          "name" : "{{@Var.name}}",
          "orgPlan" : "{{@Var.orgPlan}}",
          "version" : "{{@Var.version}}"
        },
        "region" : "{{@Var.region}}",
        "version" : "{{@Var.version}}"
      },
      "buildProperties" : "{{@Var.buildProperties}}",
      "cloudType" : "{{@Var.cloudType}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "dockerSwarmScript" : "{{@Var.dockerSwarmScript}}",
      "driver" : "{{@Var.driver}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "ipAddress" : "{{@Var.ipAddress}}",
      "key" : "{{@Var.key}}",
      "kubernetesManualScript" : "{{@Var.kubernetesManualScript}}",
      "kubernetesSwarmScript" : "{{@Var.kubernetesSwarmScript}}",
      "lastPingTime" : null,
      "live" : "{{@Var.live}}",
      "manual" : false,
      "manualScript" : "{{@Var.manualScript}}",
      "max" : "{{@Var.max}}",
      "min" : "{{@Var.min}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "name" : "{{@Var.name}}",
      "nodeId" : "{{@Var.nodeId}}",
      "org" : {
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "orgPlan" : "{{@Var.orgPlan}}",
        "version" : "{{@Var.version}}"
      },
      "ownerName" : "{{@Var.ownerName}}",
      "region" : "{{@Var.region}}",
      "startTime" : "{{@Var.startTime}}",
      "status" : "{{@Var.status}}",
      "timeZone" : "{{@Var.timeZone}}",
      "version" : "{{@Var.version}}",
      "visibility" : "{{@Var.visibility}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
