---
parent: Api_v1_skills
name: ApiV1SkillsPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/skills
endpoint: /api/v1/skills
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "accessKey" : "{{@Var.accessKey}}",
      "createdBy" : "{{@Var.createdBy}}",
      "createdDate" : "{{@Var.createdDate}}",
      "description" : "{{@Var.description}}",
      "host" : "{{@Var.host}}",
      "id" : "{{@Var.id}}",
      "inactive" : false,
      "key" : "{{@Var.key}}",
      "modifiedBy" : "{{@Var.modifiedBy}}",
      "modifiedDate" : "{{@Var.modifiedDate}}",
      "name" : "{{@Var.name}}",
      "opts" : [ {
        "id" : "",
        "label" : "{{@Random}}",
        "mandatory" : false,
        "value" : "{{@Random}}"
      } ],
      "org" : {
        "createdBy" : "{{@Var.createdBy}}",
        "createdDate" : "{{@Var.createdDate}}",
        "id" : "{{@Var.id}}",
        "inactive" : false,
        "modifiedBy" : "{{@Var.modifiedBy}}",
        "modifiedDate" : "{{@Var.modifiedDate}}",
        "name" : "{{@Var.name}}",
        "orgPlan" : "{{@Var.orgPlan}}",
        "version" : "{{@Var.version}}"
      },
      "prop1" : "{{@Var.prop1}}",
      "prop2" : "{{@Var.prop2}}",
      "prop3" : "{{@Var.prop3}}",
      "prop4" : "{{@Var.prop4}}",
      "prop5" : "{{@Var.prop5}}",
      "secretKey" : "{{@Var.secretKey}}",
      "skillType" : "{{@Var.skillType}}",
      "version" : "{{@Var.version}}"
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
  showResponse: true
autoGenerated: true
